id: P1092847D
initial_creation_type: input
source_metadata:
  title: Jonang Series
  language: bo
  description: 'Texts related to the Jonang (jo nang) School of Tibetan Buddhism:'
  volume:
    c7e924c668254c17a79212dbaea71783:
      title: Aspiration Prayer for the Flourishing of the Jonang Teachings
      parent: Aspiration Prayers
created_at: '2022-03-01T04:00:58.716918'
last_modified_at: '2022-03-01T04:00:58.716921'
statistics:
  total_words: 421
  total_non_words: 44
quality:
  non_words_ratio: 0.1
